# Javascript Node CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-javascript/ for more details

version: 2

jobs:
  basic-test:
    filters:
      branches:
        only:
          - /release\/sprint-.*/
          - master
          - /PONY-.*/

    # Docker version is documented at https://circleci.com/docs/2.0/circleci-images/
    docker:
    - image: circleci/node:8.11.4

    steps:
    - checkout

    - run:
        name: Install dependencies
        command: npm install

    - run:
        name: Build the PWA app
        command: npm run build
  
  deep-test:
  filters:
    branches:
      only: 
        - /release\/sprint-.*/
        - master

    # Docker version is documented at https://circleci.com/docs/2.0/circleci-images/
    docker:
    - image: circleci/node:8.11.4

    run:
        name: Check README file
        command: cat README.md

notify:
  webhooks:
    - url: https://outlook.office.com/webhook/d4396a6d-63d2-48a5-83c9-db5feeee255c@fd206715-7509-4ae5-9b96-76bb97886a84/CircleCI/4c91e9b910e64935aa5c90e6d8733aa6/3877cbd7-4b44-4863-b3b4-4d1b5ea505a1

workflows:
  version: 2
  test:
    jobs:
      - basic-test
      - deep-test