# Javascript Node CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-javascript/ for more details

version: 2

jobs:
  build:
    docker:
    # specify the version you desire here. 
    # Version is documented at https://circleci.com/docs/2.0/circleci-images/
    - image: circleci/node:8.11.4

    steps:
    - checkout

    # Download and cache dependencies
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-

    - run: npm install

    # Run npm build test !!!
    - run: npm run build

notify:
  webhooks:
    - url: https://outlook.office.com/webhook/d4396a6d-63d2-48a5-83c9-db5feeee255c@fd206715-7509-4ae5-9b96-76bb97886a84/CircleCI/4c91e9b910e64935aa5c90e6d8733aa6/3877cbd7-4b44-4863-b3b4-4d1b5ea505a1
